# Generated by Django 6.1 on 2026-09-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_options_accomodattion_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomodattion',
            options={'verbose_name': 'Проживание', 'verbose_name_plural': 'Проживаний'},
        ),
    ]
