# Generated by Django 6.1 on 2026-09-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_accomodattion_options_alter_provision_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='accomodattion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.accomodattion'),
        ),
        migrations.AddField(
            model_name='provision',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.service'),
        ),
    ]
