# Generated by Django 6.1 on 2026-09-15 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_provision_accomodattion_provision_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user_provision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provision',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_user_provision', to=settings.AUTH_USER_MODEL),
        ),
    ]
