# Generated by Django 6.1 on 2026-09-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_provision_client_provision_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provision',
            options={'verbose_name': 'Оказание услуги', 'verbose_name_plural': 'Оказанные услуги'},
        ),
        migrations.RemoveField(
            model_name='provision',
            name='client',
        ),
    ]
