# Generated by Django 6.1 on 2026-09-23 04:59

from django.db import migrations
from hotel.models import Profile as NewProfile


def fill_profiles_for_user(apps, schema_editor):
    Profile = apps.get_model("hotel", "Profile")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        if not hasattr(user, 'profile'):
            Profile.objects.create(user=user, role=NewProfile.Role.undefined)

class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RunPython(fill_profiles_for_user, reverse_code=None)
    ]
