# Generated by Django 6.1 on 2026-09-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='picture',
            field=models.ImageField(null=True, upload_to='hotel', verbose_name='Изображение'),
        ),
    ]
