# Generated by Django 6.1 on 2026-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_room_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(null=True, upload_to='hotel', verbose_name='Изображение'),
        ),
    ]
