# Generated by Django 6.1 on 2026-09-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_remove_room_picture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='picture',
            new_name='image',
        ),
    ]
