# Generated by Django 6.1 on 2026-09-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_rename_picture_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='picture',
        ),
    ]
