# Generated by Django 6.1 on 2026-09-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_rename_image_image_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='hotel.room'),
        ),
    ]
